packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.90.21
  "@trpc/client": ^11.3.1
  "@trpc/react-query": ^11.3.1
  "@trpc/server": ^11.3.1
  eslint: ^9.39.2
  prettier: ^3.5.3
  tailwindcss: ^4.2.1
  typescript: ^5.8.3
  zod: ^3.25.76

catalogs:
  react18:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6
